USE [master]
GO

/****** Object:  Database [Quanlichitieu]    Script Date: 12/10/2020 21:56:40 ******/
CREATE DATABASE [Quanlichitieu] ON  PRIMARY 
( NAME = N'Quanlichitieu', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Quanlichitieu.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Quanlichitieu_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Quanlichitieu_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Quanlichitieu] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Quanlichitieu].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Quanlichitieu] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Quanlichitieu] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Quanlichitieu] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Quanlichitieu] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Quanlichitieu] SET ARITHABORT OFF 
GO

ALTER DATABASE [Quanlichitieu] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Quanlichitieu] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Quanlichitieu] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Quanlichitieu] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Quanlichitieu] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Quanlichitieu] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Quanlichitieu] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Quanlichitieu] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Quanlichitieu] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Quanlichitieu] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Quanlichitieu] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Quanlichitieu] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Quanlichitieu] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Quanlichitieu] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Quanlichitieu] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Quanlichitieu] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Quanlichitieu] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Quanlichitieu] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Quanlichitieu] SET  READ_WRITE 
GO

ALTER DATABASE [Quanlichitieu] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Quanlichitieu] SET  MULTI_USER 
GO

ALTER DATABASE [Quanlichitieu] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Quanlichitieu] SET DB_CHAINING OFF 
GO


